from fastapi import FastAPI, Form, Header, HTTPException, Query
from fastapi.responses import Response
from pydantic import BaseModel
from typing import Any, Dict, Optional
import uvicorn
import time
import io
import re
import uuid
from pathlib import Path
import os
import pandas as pd

import db

app = FastAPI()

# -----------------------------------------------------------------------------------------
# JOB TRACKING -- backed by MySQL via db.py (users / projects / jobs tables in schema.sql)
# -----------------------------------------------------------------------------------------
# job_id vs. job_uuid — two distinct identifiers, mirroring JOBS in the ERD:
#   - job_uuid: generated by the backend (submit_analysis(), below) when
#     the job is created, and returned once in the POST /jobs response.
#   - job_id: a display-friendly label derived from the job row's real
#     MySQL auto-increment primary key 
PIPELINE_STEPS = ["Reading Data", "In silico Digestion", "Bioactivity Matching", "Generating Results"]

job_notifications: Dict[str, dict] = {}


def _format_job_id(db_id: int) -> str:
    """Turns a job row's real MySQL auto-increment id into the same
    'JOB000001'-style label this API always returned, back when job_id came
    from an in-memory counter instead of a real primary key."""
    return f"JOB{db_id:06d}"


# ---------- Demo user (stand-in until login is real) ---------------------------------------
_DEMO_USERNAME = "admin"
_DEMO_EMAIL = "admin@smartbiopep.local"


def _get_or_create_demo_user() -> int:
    user = db.get_user_by_username(_DEMO_USERNAME)
    if user is not None:
        return user["id"]
    # password_hash=None -- login() doesn't check this yet, so writing a
    # fake hash here would just be misleading about what's actually secured.
    return db.create_user(_DEMO_USERNAME, _DEMO_EMAIL, password_hash=None)

# -----------------------------------------------------------------------------------------
# COMPLETION EMAIL
# -----------------------------------------------------------------------------------------
# Where the frontend's Dashboard page lives -- the link mailed out below opens
# straight to this job's results (?job_uuid=...), same identifier every other
# API call uses.
# This must be a browser-reachable URL, NOT an internal Docker service name --
# it's mailed to the user and opened from their own machine, so it has to be
# whatever address/port the frontend container is actually published on
# (e.g. http://localhost:8501 in local dev, or a real public domain once
# deployed). Override via env var; the localhost default only works for
# running everything on one machine outside Docker.
RESULT_BASE_URL = os.environ.get("SMARTBIOPEP_APP_URL", "http://localhost:8501") + "/Dashboard"


def _send_completion_email(email: str, job_uuid: str) -> str:
    result_url = f"{RESULT_BASE_URL}?job_uuid={job_uuid}"
    print(
        f"[mock email] To: {email}\n"
        f"[mock email] Subject: Your SmartBioPep job is ready\n"
        f"[mock email] Body: Your analysis has finished. View your results: {result_url}"
    )
    return result_url

# -----------------------------------------------------------------------------------------
# REAL RESULT FILES (replaces the random-data mock for summary + sequences)
# -----------------------------------------------------------------------------------------
SAMPLE_RESULT_DIR = Path(__file__).resolve().parent / "Result_Sequence"

# Matches "RankBioactivity_G1_2Enz", "RankBioactivity_G3a_2Enz", etc.
# group 1 = the numeric part ("1", "3"), group 2 = the optional sub-letter ("", "a", "b")
STAT_FILE_PATTERN = re.compile(r'^RankBioactivity_G(\d+)([a-z]?)(?:_\d+Enz)?$')

def _group_label_from_filename(stem: str) -> Optional[str]:
    """'RankBioactivity_G3a_2Enz' -> 'Group 3a'; returns None if it doesn't match."""
    m = STAT_FILE_PATTERN.match(stem)
    if not m:
        return None
    num, letter = m.groups()
    return f"Group {num}{letter}"


def _simulate_worker_output_path(job_uuid: str) -> str:
    """Simulates the worker writing its output to disk, and returns the"""
    return str(SAMPLE_RESULT_DIR)


# -----------------------------------------------------------------------------------------
# 1. LOGIN (02_Login.py)
# -----------------------------------------------------------------------------------------
# 02_Login.py posts `data={...}` (form-encoded), so this reads form fields, not a JSON body.
@app.post("/login")
def login(username: str = Form(...), password: str = Form(...)):
    if username == "admin" and password == "password":
        return {"access_token": "fake_mock_jwt_token_12345"}
    raise HTTPException(status_code=401, detail="Invalid credentials")

# -----------------------------------------------------------------------------------------
# 2. UPLOAD & SUBMISSION (03_Data_prep.py)
# -----------------------------------------------------------------------------------------
class AnalyzePayload(BaseModel):
    project_name: str
    sample_name: Optional[str] = None
    list_bioactivities_id: list[int]
    fasta_content: str
    # Catch any other fields dynamically
    model_config = {"extra": "allow"}

@app.post("/jobs")
def submit_analysis(payload: AnalyzePayload, authorization: Optional[str] = Header(None)):
    if not authorization:
        raise HTTPException(status_code=401, detail="Missing Token")

    # ──── GENERATE job_uuid ──────────────────────────────────────
    job_uuid = str(uuid.uuid4())

    user_id = _get_or_create_demo_user()

    # Every submission becomes its own PROJECTS row -- the frontend has no
    # separate "create a project" step distinct from submitting a job, so a
    # fresh project per submission mirrors how it's actually used today.
    extra_fields = payload.model_dump()
    project_id = db.create_project(
        user_id,
        project_name=payload.project_name,
        description=extra_fields.get("description"),
    )

    # input_fasta_path stays null: the raw sequence text is sent inline in
    # this request rather than written to a file first (see the matching
    # note in schema.sql's header) -- a real worker would write it to disk
    # and this column would point at that file.
    db.create_job(
        job_uuid,
        project_id,
        input_fasta_path=None,
        list_bioactivity_id=payload.list_bioactivities_id,
        list_step_total=PIPELINE_STEPS,
    )
    # create_job() always inserts with status='PENDING' (schema.sql's
    # default) -- immediately advance it to RUNNING so behavior matches
    # what this endpoint always returned: a job that's already underway by
    # the time the frontend gets its response back.
    db.update_job_progress(job_uuid, status="RUNNING", started_at_now=True)

    row = db.get_job_by_uuid(job_uuid)
    job_id = _format_job_id(row["id"])
    return {"job_id": job_id, "job_uuid": job_uuid, "message": "Job started"}

# -----------------------------------------------------------------------------------------
# 3. MOCK EMAIL NOTIFICATION (04_Job_status.py)
# -----------------------------------------------------------------------------------------
class EmailPayload(BaseModel):
    job_uuid: str
    email: str

# Need change in this function:
# to use the email already on file for the logged-in user (once login
# actually resolves to a real users row) instead of a value typed fresh
# here every time.
@app.post("/notifications")
def subscribe_email(payload: EmailPayload, authorization: Optional[str] = Header(None)):
    if not authorization:
        raise HTTPException(status_code=401, detail="Missing Token")
    if db.get_job_by_uuid(payload.job_uuid) is None:
        raise HTTPException(status_code=404, detail="Job not found")

    # Persisted in job_notifications (not MySQL -- see the note near its
    # declaration above) so GET /jobs/{job_uuid} can "send" the completion
    # email itself once the job actually finishes, instead of here (the job
    # has usually barely started at subscribe time).
    job_notifications.setdefault(payload.job_uuid, {})["notify_email"] = payload.email
    return {"message": f"Subscribed {payload.email} successfully!"}

# -----------------------------------------------------------------------------------------
# 4. MOCK STATUS POLLING (04_Job_status.py)
# -----------------------------------------------------------------------------------------
@app.get("/jobs/{job_uuid}")
def get_status(job_uuid: str, authorization: Optional[str] = Header(None)):
    if not authorization:
        raise HTTPException(status_code=401, detail="Missing Token")

    row = db.get_job_by_uuid(job_uuid)
    if row is None:
        raise HTTPException(status_code=404, detail="Job not found")

    list_step_total = row["list_step_total"] or PIPELINE_STEPS
    step_current = row["step_current"]
    status = row["status"]
    output_result_path = row["output_result_path"]
    already_success = status == "SUCCESS"

    # Simulate progress: Move forward one step every time Streamlit asks
    if step_current < len(list_step_total):
        step_current += 1
        db.update_job_progress(job_uuid, step_current=step_current)

    # If it reaches the end, mark it as SUCCESS and (simulating the worker)
    # write the output_result_path that the frontend should now check for.
    # Guarded by already_success so a job that's already SUCCESS doesn't
    # get its completed_at timestamp re-stamped on every later poll.
    if step_current >= len(list_step_total):
        status = "SUCCESS"
        if not output_result_path:
            output_result_path = _simulate_worker_output_path(job_uuid)
        if not already_success:
            db.update_job_progress(
                job_uuid,
                status=status,
                output_result_path=output_result_path,
                completed_at_now=True,
            )

    # Fire the completion email exactly once, and only if an email was
    # actually subscribed for this job (POST /notifications). Tracked in
    # job_notifications, not the DB row -- see the note near its declaration.
    notif = job_notifications.get(job_uuid, {})
    result_url = notif.get("result_url")
    if notif.get("notify_email") and not notif.get("result_email_sent"):
        result_url = _send_completion_email(notif["notify_email"], job_uuid)
        notif["result_url"] = result_url
        notif["result_email_sent"] = True

    return {
        "job_id": _format_job_id(row["id"]),
        "status": status,
        "step_current": step_current,
        "list_step_total": list_step_total,
        "output_result_path": output_result_path,  # null until SUCCESS
        "result_url": result_url,  # null until the email has gone out
    }

# -----------------------------------------------------------------------------------------
# 5. JOB RESULT -- statistics only (05_Dashboard.py)
# -----------------------------------------------------------------------------------------
@app.get("/jobs/{job_uuid}/result")
def get_job_result(job_uuid: str, authorization: Optional[str] = Header(None)):
    """
    Statistical summary for the Dashboard's charts/tables: job status/error
    plus the 4 RankBioactivity_G*_2Enz.csv files. Does NOT include peptide
    sequence data 
    Returns:
      - job_id, status, error_message: current job state. error_message is
        always present (None unless the job failed) so the frontend has one
        place to check instead of parsing HTTP status codes for it.
      - stat_files: {group_label: [{"Bioactivity", "nPepSeq"}, ...]}, read
        from this job's RankBioactivity_G*_2Enz.csv files.

    stat_files is empty ({}) until the job actually reaches SUCCESS (i.e.
    output_result_path is set) -- the frontend should treat that the same
    way it used to treat the old endpoint's 409: "still processing," not an
    error. authorization/existence problems (missing token, unknown job,
    corrupt result files) still raise real HTTP errors, since those are
    protocol-level failures, not job states.
    """
    if not authorization:
        raise HTTPException(status_code=401, detail="Missing Token")

    row = db.get_job_by_uuid(job_uuid)
    if row is None:
        raise HTTPException(status_code=404, detail="Job not found")

    output_path = row["output_result_path"]
    stat_files: Dict[str, list] = {}

    if output_path:
        job_output_dir = Path(output_path).resolve()
        if not job_output_dir.is_dir():
            raise HTTPException(status_code=500, detail=f"output_result_path does not exist on disk: {output_path}")

        # Stat files: RankBioactivity_G*_2Enz.csv (columns: Bioactivity, nPepSeq)
        for path in sorted(job_output_dir.glob("RankBioactivity_*.csv")):
            group_label = _group_label_from_filename(path.stem)
            if group_label is None:
                continue  # skip anything that doesn't match the expected naming pattern

            # encoding="utf-8-sig" strips the leading BOM these files were saved with
            # (otherwise the first column reads as "﻿Bioactivity", not "Bioactivity")
            df = pd.read_csv(path, encoding="utf-8-sig")
            missing = {"Bioactivity", "nPepSeq"} - set(df.columns)
            if missing:
                raise HTTPException(status_code=500, detail=f"{path.name} is missing columns: {sorted(missing)}")
            stat_files[group_label] = df.to_dict(orient="records")

    return {
        "job_id": _format_job_id(row["id"]),
        "status": row["status"],
        "error_message": row["error_message"],
        "stat_files": stat_files,
    }

# -----------------------------------------------------------------------------------------
# 6. SEQUENCE DOWNLOAD -- one bioactivity's peptide sequences, on demand (05_Dashboard.py)
# -----------------------------------------------------------------------------------------
@app.get("/jobs/{job_uuid}/download")
def download_sequence_file(
    job_uuid: str,
    group: str = Query(..., description='e.g. "Group 1", "Group 3a"'),
    bioactivity: str = Query(..., description='e.g. "ACE_inhibitor" -- the raw name, matching the CSV filename'),
    authorization: Optional[str] = Header(None),
):
    """
    On-demand counterpart to GET /jobs/{job_uuid}/result: returns the real peptide-sequence CSV for
    exactly the one group + bioactivity the user clicked "Download" for,
    """
    if not authorization:
        raise HTTPException(status_code=401, detail="Missing Token")

    row = db.get_job_by_uuid(job_uuid)
    if row is None:
        raise HTTPException(status_code=404, detail="Job not found")

    output_path = row["output_result_path"]
    if not output_path:
        raise HTTPException(
            status_code=409,
            detail="Job results are not ready yet. Wait for status to reach SUCCESS before requesting a download.",
        )

    job_output_dir = Path(output_path).resolve()
    if not job_output_dir.is_dir():
        raise HTTPException(status_code=500, detail=f"output_result_path does not exist on disk: {output_path}")

    # "Group 1" -> "G1" -> the ResultG1/ subfolder this job's sequence files live under.
    group_id = group.replace("Group ", "G")
    candidate = (job_output_dir / f"Result{group_id}" / f"{bioactivity}.csv").resolve()
    # Defend against path traversal via the group/bioactivity query params
    # (e.g. bioactivity="../../etc/passwd") -- reject anything that would
    # resolve outside job_output_dir before touching the filesystem.
    if job_output_dir not in candidate.parents:
        raise HTTPException(status_code=400, detail="Invalid group or bioactivity value")
    if not candidate.is_file():
        raise HTTPException(status_code=404, detail=f"No sequence file for group={group}, bioactivity={bioactivity}")

    return Response(content=candidate.read_text(encoding="utf-8-sig"), media_type="text/csv")

if __name__ == "__main__":
    # 0.0.0.0, not 127.0.0.1: inside a container, 127.0.0.1 only accepts
    # connections from within that same container, so the frontend (a
    # different container) would never be able to reach this API even
    # though the port is published/mapped correctly.
    uvicorn.run(app, host="0.0.0.0", port=8000)
